In [1]:
# Kita akan melihat data yang akan digunakan untuk pembelajaran
# Kita gunakan Pandas untuk melihat terlebih dahulu
import pandas as pd


In [4]:
df = pd.read_csv('world_alcohol.csv')
df.head()

Year       WHO region                Country Beverage Types  Display Value
0  1986  Western Pacific               Viet Nam           Wine           0.00
1  1986         Americas                Uruguay          Other           0.50
2  1985           Africa           Cte d'Ivoire           Wine           1.62
3  1986         Americas               Colombia           Beer           4.27
4  1987         Americas  Saint Kitts and Nevis           Beer           1.98

# Pengenalan NumPy

In [5]:
# Untuk mengimport modul NumPy kita gunakan
import numpy

In [6]:
# Untuk membuat lebih gampang seperti pertemuan sebelumnya kita gunakan alias 'as'
import numpy as np

In [7]:
vektor = np.array([5, 10, 15, 20])
vektor 

array([ 5, 10, 15, 20])

In [8]:
matriks = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
matriks

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [9]:
# Tugas 1
# Buatlah sebuah vektor dengan nama vektor_tes  dari sebuah list [1, 2, 3]
# Buatlah sebuah matriks dengan nama matriks_tes dengan
# list [[1, 2, 3], [2, 4, 8], [3, 9, 27]]

# Tuliskan Kode kamu di bawah ini






In [10]:
# Tunjukkan vektor_tes dan matriks_tes di bawah ini

# Array Shape

In [18]:
# Vektor memiliki beberapa element contoh dibawah ini memiliki 5 element
df.head(1)

Year       WHO region   Country Beverage Types  Display Value
0  1986  Western Pacific  Viet Nam           Wine            0.0

In [19]:
# Kemudian matriks ini memiliki 5 Kolom dan 3 Baris
# Ingat index bermula dari 0
df.head(3)

Year       WHO region       Country Beverage Types  Display Value
0  1986  Western Pacific      Viet Nam           Wine           0.00
1  1986         Americas       Uruguay          Other           0.50
2  1985           Africa  Cte d'Ivoire           Wine           1.62

In [22]:
# Pada numpy kita bisa mengetahui bentuk dari suatu data dengan menggunakan atribut shape
# vektor = np.array([5, 10, 15, 20])
vektor.shape

(4,)

In [23]:
# matriks = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
matriks.shape

(3, 3)

In [24]:
# Tugas 2 
# Tunjukan bentuk dari vektor_tes dan matriks_tes 

# Tulis kode kamu di bawah ini




# Data Type

In [25]:
# Kita bisa menunjukkan tipe data dengan menggunakan
vektor.dtype

dtype('int64')

In [26]:
matriks.dtype

dtype('int64')

In [28]:
float_vektor = np.random.randn(5)
float_vektor

array([ 0.85882008,  1.02054133, -1.93768514, -0.92854636, -0.6051109 ])

In [29]:
float_vektor.dtype

dtype('float64')

In [30]:
# Tugas 3 
# Tunjukan tipe data dari vektor_tes dan matriks_tes 

# Tulis kode kamu di bawah ini



# Indexing Arrays

In [36]:
# Memilih indeks pada numpy hampir sama dengan list
vektor

array([ 5, 10, 15, 20])

In [37]:
vektor[1]

10

In [38]:
matriks

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [39]:
matriks[1,2]

30

In [51]:
# Saatnya menggunkana data sebenarnya
alkohol_dunia = df.as_matrix()
alkohol_dunia

array([[1986, 'Western Pacific', 'Viet Nam', 'Wine', 0.0],
       [1986, 'Americas', 'Uruguay', 'Other', 0.5],
       [1985, 'Africa', "Cte d'Ivoire", 'Wine', 1.62],
       ..., 
       [1986, 'Europe', 'Switzerland', 'Spirits', 2.54],
       [1987, 'Western Pacific', 'Papua New Guinea', 'Other', 0.0],
       [1986, 'Africa', 'Swaziland', 'Other', 5.15]], dtype=object)

In [44]:
# Tugas 4

# Tampilkan baris ke dua pada world_alcohol kedalam negara_kedua
# Tampilkan Alkohol apa dari negara pantai gading pada tahun 1985 masukkan pada pg_alkohol
# Ini terletak pada baris ke tiga kolom ke empat

# Tulis kode kalian di bawah ini



# Slicing Arrays

In [45]:
# Mengambil bagian dari array hampir sama dengan list

vektor

array([ 5, 10, 15, 20])

In [46]:
vektor[:2]

array([ 5, 10])

In [47]:
matriks

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [49]:
matriks[:,1]

array([10, 25, 40])

In [50]:
# Pengingat data
df.head()

Year       WHO region                Country Beverage Types  Display Value
0  1986  Western Pacific               Viet Nam           Wine           0.00
1  1986         Americas                Uruguay          Other           0.50
2  1985           Africa           Cte d'Ivoire           Wine           1.62
3  1986         Americas               Colombia           Beer           4.27
4  1987         Americas  Saint Kitts and Nevis           Beer           1.98

In [52]:
# Tugas 5

# Masukkan semua negara pada alkohol_dunia pada semua_negara
# Masukkan semua konsumsi alkohol_dunia pada konsumsi_alkohol
# Tunjukkan hasilnya


# Tulis kode kamu di bawah ini




# Slicing one dimension

In [54]:
matriks

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [57]:
# kita ingin mengambil semua baris dengan dua kolom pertama kita dapat tulis
matriks[:,0:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [58]:
# Sebaliknya jika ingin dua baris terakhir semua kolom kita dapat tulis
matriks[1:3,:]

array([[20, 25, 30],
       [35, 40, 45]])

In [59]:
# Bahkan kita dapat hanya mengambil satu kolom saja dari baris yang ditentukan
matriks[1:3,1]

array([25, 40])

In [60]:
# Tugas 6

# 1. Masukkan semua baris dan dua kolom pertama dunia_alkohol pada dua_kolom_pertama
# 2. Masukkan 10 baris pertama dan semua kolom dunia_alkohol pada sepuluh_baris_pertama
# 3. Masukkan 10 baris partama dan kolom pertama dunia_alkohol pada sepuluh_tahun_pertama


# Tulis kode kamu di bawah ini





In [61]:
# Tugas 7

# 1. Maskukkan 20 baris pertama dan kolom dengan index 1 dengan 2 dunia_alkohol pada dua_puluh_regional